Added .yml extra final check when all attempts fail Added .should('be.visible') to make sure cookie Buttons Wrapper is displayed to user

diff --git a/.github/workflows/TASK_3.yml b/.github/workflows/TASK_3.yml
--- a/.github/workflows/TASK_3.yml
+++ b/.github/workflows/TASK_3.yml
@@ -53,4 +53,10 @@ jobs:
         if: failure() && matrix.attempt != '2'
         run: echo "Attempt ${{ matrix.attempt }} failed, retrying..."
 
+      - name: Final check
+        if: failure() && matrix.attempt == '2'
+        run: |
+          echo  "All attempts failed"
+          exit 1
+
 
